/* Generated by tool/gen_certificates.js — do not edit by hand. */
export const CERTIFICATES = [
  {
    "slug": "cum-laude-distinction-2024",
    "title": "Academic Distinction — Cum Laude",
    "issuer": "South East Asian Institute of Technology",
    "date": "June 2024",
    "detail": "BS Information Technology · 16th Commencement Exercises"
  },
  {
    "slug": "champion-psit-programming-2023",
    "title": "Computer Programming — Champion",
    "issuer": "PSITE–PSITS Region XII",
    "date": "April 2023",
    "detail": "Award of Excellence · 11th PSIT Regional Convention, General Santos City"
  },
  {
    "slug": "hackforgov-3rd-place-2023",
    "title": "HACKFORGOV Capture-the-Flag — 3rd Place",
    "issuer": "SEAIT — College of ICT",
    "date": "October 2023",
    "detail": "Award of Excellence for 3rd place in the DICT HACKFORGOV 2023 competition"
  },
  {
    "slug": "deans-list-academic-excellence-2023",
    "title": "Academic Excellence — Dean’s List",
    "issuer": "South East Asian Institute of Technology",
    "date": "AY 2022–2023",
    "detail": "General weighted average of 1.03"
  },
  {
    "slug": "national-it-skills-c-2024",
    "title": "National IT Skills Competition — C Programming",
    "issuer": "Integrated Society of IT Enthusiasts (iSITE)",
    "date": "April 2024",
    "detail": "7th place nationally among 28 competitors"
  },
  {
    "slug": "yfc-provincial-eligibility-2023",
    "title": "Young Farmers Challenge — Provincial Level",
    "issuer": "Department of Agriculture",
    "date": "July 2023",
    "detail": "Eligibility for the provincial start-up competition (FarmFinds) · co-awarded with Angelyn C. Sua-an"
  },
  {
    "slug": "yfc-business-pitching-regional-2023",
    "title": "Young Farmers Challenge — Regional Business Pitching",
    "issuer": "DA Regional Field Office XII",
    "date": "October 2023",
    "detail": "Regional Level Start-Up competition, Open Category · co-awarded with Angelyn C. Sua-an"
  },
  {
    "slug": "hackforgov-participation-2023",
    "title": "HACKFORGOV CTF 2023",
    "issuer": "Department of ICT",
    "date": "September 2023",
    "detail": ""
  },
  {
    "slug": "psits-12th-convention-innotech-2024",
    "title": "12th PSITS Regional Convention — InnoTech Gala",
    "issuer": "PSITE Region XII",
    "date": "May 2024",
    "detail": ""
  },
  {
    "slug": "seminar-python-programming-2023",
    "title": "Python Programming Workshop",
    "issuer": "SEAIT — College of ICT",
    "date": "June 2023",
    "detail": ""
  },
  {
    "slug": "seminar-web-development-2023",
    "title": "Web Development from Scratch",
    "issuer": "SEAIT — College of ICT",
    "date": "June 2023",
    "detail": ""
  },
  {
    "slug": "seminar-leadership-strategic-planning-2023",
    "title": "Leadership Skills & Strategic Planning",
    "issuer": "SEAIT Supreme Student Council",
    "date": "March 2023",
    "detail": ""
  },
  {
    "slug": "hackathon-2023-appreciation",
    "title": "Hackathon 2023 — Appreciation",
    "issuer": "SEAIT — College of ICT",
    "date": "March 2023",
    "detail": ""
  },
  {
    "slug": "seminar-ai-in-education-2023",
    "title": "Tech Talk — Revolutionizing Education with AI",
    "issuer": "PSITE–PSITS Region XII",
    "date": "April 2023",
    "detail": ""
  },
  {
    "slug": "seminar-student-to-ceo-2023",
    "title": "Tech Talk — A Student’s Path to CEO",
    "issuer": "PSITE–PSITS Region XII",
    "date": "April 2023",
    "detail": ""
  },
  {
    "slug": "seminar-mugna-insider-tech-2023",
    "title": "Tech Talk — MUGNA: Insider Tech",
    "issuer": "PSITE–PSITS Region XII",
    "date": "April 2023",
    "detail": ""
  },
  {
    "slug": "seminar-hitchhikers-guide-tech-2023",
    "title": "Tech Talk — Hitchhiker’s Guide to the Tech Industry",
    "issuer": "PSITE–PSITS Region XII",
    "date": "April 2023",
    "detail": ""
  },
  {
    "slug": "psits-11th-convention-participation-2023",
    "title": "11th PSITS Regional Convention",
    "issuer": "PSITE–PSITS Region XII",
    "date": "April 2023",
    "detail": ""
  }
];
